export const BUSINESS_TYPE_SUGGESTIONS = [
  "Restaurant",
  "Cafe",
  "Coffee shop",
  "Juice shop",
  "Bakery",
  "Buffet restaurant",
  "Health food restaurant",
  "Health food store",
  "Vegan restaurant",
  "Vegetarian restaurant",
  "Halal restaurant",
  "Kosher restaurant",
  "Mediterranean restaurant",
  "Salad bowl",
  "Smoothie shop",
  "Acai bowl",
  "Pizza restaurant",
  "Sushi restaurant",
  "Italian restaurant",
  "Mexican restaurant",
  "Chinese restaurant",
  "Indian restaurant",
  "Thai restaurant",
  "Japanese restaurant",
  "Vietnamese restaurant",
  "Caribbean restaurant",
  "Hot pot restaurant",
];

export const DIETARY_TAG_SUGGESTIONS = [
  "vegan",
  "vegetarian",
  "kosher",
  "halal",
  "gluten-free",
  "dairy-free",
  "paleo",
  "keto",
  "raw",
  "organic",
  "farm-to-table",
  "juice",
  "salad-bowl",
  "whole-foods",
  "low-calorie",
];
